### ISSUE TITLE
tt-smi [v2.0.1] reporting incorrect link speed and link width

### ISSUE THREAD

**Issue by milank94** [tenstorrent/luwen#5]
I'm running the latest tt-smi tool from: https://github.com/tenstorrent/tt-smi and observing that the reported Link Speed is Gen1 and the Link Width is x1 on a system with a Wormhole N150.
![image](https://github.com/tenstorrent/luwen/assets/78221808/94dc0c50-2c9e-4174-8760-16c25c8debb0)

I ran an older version of tt-smi which shows the correct data:
![image](https://github.com/tenstorrent/luwen/assets/78221808/31ffd7ad-1ffc-4cf4-aa05-df5ec5fa9dcb)

**Comment by sbansalTT** [comment]
This has been fixed with the tt-smi release of 2.1.0 
Do let me know if the issue persists
